---

- name: ssh.restart
  service: name=ssh state=restarted

- name: timezone.update
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: postfix.aliases
  command: postalias /etc/aliases

- name: postfix.restart
  service: name=postfix state=restarted
