#!/bin/bash
 
# usage: bootstrap 123.123.123.123 mybox.example.com path/to/local/id_rsa.pub
#        bootstrap mybox.example.com path/to/local/id_rsa.pub
 
# preconditions: fresh install of Debian with ssh installed/running
# effects:
#  - hostname is set
#  - `ansible` user created with disabled password and added to sudo/ssh groups
#  - specified public key added to user's authorized_keys
#  - sudoers updated to allow no password operations

if [ -z "$3" ]
then
	ADDRESS=$1
	FULL_HOSTNAME=$1
	KEY=$(cat $2)
else
	ADDRESS=$1
	FULL_HOSTNAME=$2
	KEY=$(cat $3)
fi

HOSTNAME="$(echo "$FULL_HOSTNAME" | cut -d '.' -f 1)"

ssh root@$ADDRESS <<BOOTSTRAP

#
# Hostname
 
hostname "${HOSTNAME}"
echo "127.0.1.1 ${HOSTNAME} ${FULL_HOSTNAME}" >> /etc/hosts
 
#
# Ansible user
 
adduser --disabled-password --gecos "" ansible
usermod -a -G sudo ansible
usermod -a -G ssh ansible
 
#
# SSH key for ansible user
 
mkdir -p ~ansible/.ssh
echo "$KEY" > ~ansible/.ssh/authorized_keys
chown -R ansible:ansible ~ansible/.ssh
chmod 700 ~ansible/.ssh
chmod 600 ~ansible/.ssh/authorized_keys
 
#
# Update sudoers

apt-get install sudo
cp /etc/sudoers sudoers.tmp
sed -i '/%sudo/c\%sudo ALL=(ALL:ALL) NOPASSWD: ALL' sudoers.tmp
visudo -c -f sudoers.tmp && mv sudoers.tmp /etc/sudoers
 
BOOTSTRAP
