#! /bin/sh

### BEGIN INIT INFO
# Provides:          redis-server
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts redis-server
# Description:       starts redis-server using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON={{ redis_location }}/bin/redis-server
DAEMON_ARGS={{ redis_config_file }}
NAME=redis-server
DESC=redis-server
PID_FILE={{ redis_pid_file }}

test -x $DAEMON || exit 0
test -x $DAEMONBOOTSTRAP || exit 0

set -e

case "$1" in
  
  start)
    echo -n "Starting $DESC: "
    touch $PID_FILE
    chown redis:redis $PID_FILE
    if start-stop-daemon \
        --start \
        --quiet \
        --umask 007 \
        --pidfile $PID_FILE \
        --chuid redis:redis \
        --exec $DAEMON -- $DAEMON_ARGS
    then
      echo "Done."
    else
      echo "failed"
    fi
    ;;

  stop)
    echo -n "Stopping $DESC: "
    if start-stop-daemon \
      --stop \
      --retry 10 \
      --quiet \
      --oknodo \
      --pidfile $PID_FILE \
      --exec $DAEMON
    then
      echo "Done."
    else
      echo "failed"
    fi
    rm -f $PID_FILE
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;

esac

exit 0
