---
- name: Ensure apt cache is up to date
  apt: update_cache=yes

- name: Ensure MySQL is installed
  apt: pkg={{item}} state=latest
  with_items:
    - mysql-server
    - mysql-utilities

- name: Ensure MySQL is running
  service: name=mysql state=started enabled=true
