---

- name: Add PostgreSQL apt key
  apt_key: url='https://www.postgresql.org/media/keys/ACCC4CF8.asc' state=present

- name: Add PostgreSQL apt repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main' state='present' update_cache='yes'

- name: Ensure PostgreSQL packages are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-9.3
    - postgresql-contrib
    - libpq5
    - python-psycopg2

- name: Ensure PostgreSQL is running
  service: name=postgresql state=started
