---

- name: "Ensure app root directory exists"
  file: path={{ item.path }}
        state=directory
        owner={{ item.deploy_user }}
        group={{ item.web_group }}
        mode=750
  with_items: rails_apps

- name: "Ensure app releases directory exists"
  file: path={{ item.path }}/releases
        state=directory
        owner={{ item.deploy_user }}
        group={{ item.deploy_user }}
  with_items: rails_apps

- name: "Ensure app shared directory exists"
  file: path={{ item.path }}/shared
        state=directory
        owner={{ item.deploy_user }}
        group={{ item.deploy_user }}
  with_items: rails_apps

- name: "Ensure app shared directory exists"
  file: path={{ item.path }}/shared/config
        state=directory
        owner={{ item.deploy_user }}
        group={{ item.deploy_user }}
  with_items: rails_apps

- name: "Ensure app log directory exists"
  file: path={{ item.path }}/shared/log
        state=directory
        owner={{ item.deploy_user }}
        group={{ item.web_group }}
        mode=770
  with_items: rails_apps

- name: "Ensure database.yml exists"
  template: dest={{ item.path }}/shared/config/database.yml
            src={{ item.db_template }}
  with_items: rails_apps

- name: "Ensure database.yml is only readable by web user"
  file: path={{ item.path }}/shared/config/database.yml
        owner={{ item.web_user }}
        group={{ item.web_group }}
        mode=640
  with_items: rails_apps
