---

#
# Essentials

- name: Update apt cache
  apt: update_cache=yes

- name: "Install git, ntp, links, vim"
  apt: pkg={{ item }}
  with_items:
    - git
    - ntp
    - links
    - vim

- name: Install build prerequisites
  apt: pkg={{item}}
  with_items:
    - autoconf
    - build-essential

- name: Set the system timezone
  copy: content={{ system_timezone}}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  notify:
    - timezone.update

- name: Ensure ntp is running
  service: name=ntp state=started enabled=yes

- name: Install python-software-properties so the apt_repository module will work properly
  apt: pkg=python-software-properties

#
# MOTD

- name: Update motd
  copy: src=motd dest=/etc/motd owner=root group=root mode=644

#
# Source directory for compiling packages from source

- name: Create the source directory
  sudo: no
  file: path={{ source_directory }}
        state=directory

#
# Services the way I like them

- name: Disable rpcbind
  service: name=rpcbind state=stopped enabled=no

- name: Disable exim
  service: name=exim4 state=stopped enabled=no

- name: Install postfix
  apt: pkg=postfix state=latest

- name: Ensure postfix is configured securely
  template: src=postfix_main.cf
            dest=/etc/postfix/main.cf
            owner=root
            group=root
            mode=0644
  notify: postfix.restart

- name: Ensure postfix is running
  service: name=postfix state=started enabled=yes

- name: Set up root mail alias
  lineinfile: "dest=/etc/aliases
              regexp='^root:'
              line='root: {{ root_mail_alias }}'
              state=present"
  notify: postfix.aliases

#
# SSH lockdown

- name: Ensure root login over SSH is disabled
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^PermitRootLogin
              line='PermitRootLogin no'
              state=present
  notify: ssh.restart

- name: Ensure only ssh group can log in over SSH
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^AllowGroups
              line='AllowGroups ssh'
              state=present
  notify: ssh.restart

- name: Ensure password login with SSH is disabled
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^PasswordAuthentication
              line='PasswordAuthentication no'
              state=present
  notify: ssh.restart
